;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.001

name=App-XWindowManagerUtils

[GenPericmdScript / GenPericmdScript list-kde-activities]
url=/App/KDEActivityUtils/list_kde_activities
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript list-kde-activities-stack]
url=/App/KDEActivityUtils/list_kde_activities_stack
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript return-to-previously-set-kde-activity]
url=/App/KDEActivityUtils/return_to_previously_set_kde_activity
enable_log=1
read_config=0
read_env=0

[GenPericmdScript / GenPericmdScript set-current-kde-activity]
url=/App/KDEActivityUtils/set_current_kde_activity
enable_log=1
read_config=0
read_env=0

[InsertExecsList]

[@Author::PERLANCAR]
:version=0.610

[Prereqs / TestRequires]
;Test::More=0.98

[Prereqs]
perl=5.010001
strict=0
warnings=0
Complete::Util=0.620
Exporter=5.57
IPC::ShareLite=0
IPC::System::Options=0.339
List::Util::Uniq=0.008
Log::ger=0.038

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102

